var annotated_dup =
[
    [ "arg_router", "namespacearg__router.html", [
      [ "algorithm", "namespacearg__router_1_1algorithm.html", [
        [ "find_specialisation", "classarg__router_1_1algorithm_1_1find__specialisation.html", null ],
        [ "count_specialisation", "classarg__router_1_1algorithm_1_1count__specialisation.html", null ],
        [ "count_despecialised", "classarg__router_1_1algorithm_1_1count__despecialised.html", null ],
        [ "has_specialisation", "structarg__router_1_1algorithm_1_1has__specialisation.html", null ],
        [ "zip", "classarg__router_1_1algorithm_1_1zip.html", "classarg__router_1_1algorithm_1_1zip" ],
        [ "unzip", "structarg__router_1_1algorithm_1_1unzip.html", "structarg__router_1_1algorithm_1_1unzip" ]
      ] ],
      [ "dependency", "namespacearg__router_1_1dependency.html", [
        [ "alias_group_t", "classarg__router_1_1dependency_1_1alias__group__t.html", "classarg__router_1_1dependency_1_1alias__group__t" ],
        [ "one_of_t", "classarg__router_1_1dependency_1_1one__of__t.html", "classarg__router_1_1dependency_1_1one__of__t" ]
      ] ],
      [ "multi_lang", "namespacearg__router_1_1multi__lang.html", [
        [ "root_t", "classarg__router_1_1multi__lang_1_1root__t.html", "classarg__router_1_1multi__lang_1_1root__t" ],
        [ "root_wrapper_t", "classarg__router_1_1multi__lang_1_1root__wrapper__t.html", "classarg__router_1_1multi__lang_1_1root__wrapper__t" ],
        [ "translation", "classarg__router_1_1multi__lang_1_1translation.html", null ]
      ] ],
      [ "parsing", "namespacearg__router_1_1parsing.html", [
        [ "dynamic_token_adapter", "classarg__router_1_1parsing_1_1dynamic__token__adapter.html", "classarg__router_1_1parsing_1_1dynamic__token__adapter" ],
        [ "parse_target", "classarg__router_1_1parsing_1_1parse__target.html", "classarg__router_1_1parsing_1_1parse__target" ],
        [ "pre_parse_data_base", "classarg__router_1_1parsing_1_1pre__parse__data__base.html", "classarg__router_1_1parsing_1_1pre__parse__data__base" ],
        [ "pre_parse_data", "classarg__router_1_1parsing_1_1pre__parse__data.html", null ],
        [ "pre_parse_data< Validator, false >", "classarg__router_1_1parsing_1_1pre__parse__data_3_01Validator_00_01false_01_4.html", "classarg__router_1_1parsing_1_1pre__parse__data_3_01Validator_00_01false_01_4" ],
        [ "pre_parse_data< Validator, true >", "classarg__router_1_1parsing_1_1pre__parse__data_3_01Validator_00_01true_01_4.html", "classarg__router_1_1parsing_1_1pre__parse__data_3_01Validator_00_01true_01_4" ],
        [ "token_type", "structarg__router_1_1parsing_1_1token__type.html", "structarg__router_1_1parsing_1_1token__type" ]
      ] ],
      [ "policy", "namespacearg__router_1_1policy.html", [
        [ "help_formatter_component", "namespacearg__router_1_1policy_1_1help__formatter__component.html", [
          [ "default_line_formatter", "classarg__router_1_1policy_1_1help__formatter__component_1_1default__line__formatter.html", "classarg__router_1_1policy_1_1help__formatter__component_1_1default__line__formatter" ],
          [ "default_preamble_formatter", "classarg__router_1_1policy_1_1help__formatter__component_1_1default__preamble__formatter.html", "classarg__router_1_1policy_1_1help__formatter__component_1_1default__preamble__formatter" ],
          [ "default_addendum_formatter", "classarg__router_1_1policy_1_1help__formatter__component_1_1default__addendum__formatter.html", "classarg__router_1_1policy_1_1help__formatter__component_1_1default__addendum__formatter" ]
        ] ],
        [ "validation", "namespacearg__router_1_1policy_1_1validation.html", [
          [ "common_rules", "namespacearg__router_1_1policy_1_1validation_1_1common__rules.html", [
            [ "despecialised_any_of_rule", "structarg__router_1_1policy_1_1validation_1_1common__rules_1_1despecialised__any__of__rule.html", null ]
          ] ],
          [ "utility", null, [
            [ "insert_rule", "structarg__router_1_1policy_1_1validation_1_1utility_1_1insert__rule.html", "structarg__router_1_1policy_1_1validation_1_1utility_1_1insert__rule" ],
            [ "remove_rule", "structarg__router_1_1policy_1_1validation_1_1utility_1_1remove__rule.html", "structarg__router_1_1policy_1_1validation_1_1utility_1_1remove__rule" ],
            [ "remove_rule_by_type", "classarg__router_1_1policy_1_1validation_1_1utility_1_1remove__rule__by__type.html", "classarg__router_1_1policy_1_1validation_1_1utility_1_1remove__rule__by__type" ],
            [ "update_rule", "structarg__router_1_1policy_1_1validation_1_1utility_1_1update__rule.html", "structarg__router_1_1policy_1_1validation_1_1utility_1_1update__rule" ],
            [ "update_rule_by_type", "classarg__router_1_1policy_1_1validation_1_1utility_1_1update__rule__by__type.html", "classarg__router_1_1policy_1_1validation_1_1utility_1_1update__rule__by__type" ],
            [ "add_to_rule_types", "classarg__router_1_1policy_1_1validation_1_1utility_1_1add__to__rule__types.html", "classarg__router_1_1policy_1_1validation_1_1utility_1_1add__to__rule__types" ],
            [ "add_to_rule_types_by_rule", "classarg__router_1_1policy_1_1validation_1_1utility_1_1add__to__rule__types__by__rule.html", "classarg__router_1_1policy_1_1validation_1_1utility_1_1add__to__rule__types__by__rule" ]
          ] ],
          [ "validator", "classarg__router_1_1policy_1_1validation_1_1validator.html", "classarg__router_1_1policy_1_1validation_1_1validator" ],
          [ "despecialised_unique_in_owner", "structarg__router_1_1policy_1_1validation_1_1despecialised__unique__in__owner.html", null ],
          [ "policy_unique_from_owner_parent_to_mode_or_root", "structarg__router_1_1policy_1_1validation_1_1policy__unique__from__owner__parent__to__mode__or__root.html", null ],
          [ "parent_index_pair_type", "structarg__router_1_1policy_1_1validation_1_1parent__index__pair__type.html", "structarg__router_1_1policy_1_1validation_1_1parent__index__pair__type" ],
          [ "parent_types", "structarg__router_1_1policy_1_1validation_1_1parent__types.html", null ],
          [ "must_have_policies", "structarg__router_1_1policy_1_1validation_1_1must__have__policies.html", null ],
          [ "must_not_have_policies", "structarg__router_1_1policy_1_1validation_1_1must__not__have__policies.html", null ],
          [ "child_must_have_policy", "structarg__router_1_1policy_1_1validation_1_1child__must__have__policy.html", null ],
          [ "child_must_not_have_policy", "structarg__router_1_1policy_1_1validation_1_1child__must__not__have__policy.html", null ],
          [ "policy_parent_must_not_have_policy", "structarg__router_1_1policy_1_1validation_1_1policy__parent__must__not__have__policy.html", null ],
          [ "single_anonymous_mode", "structarg__router_1_1policy_1_1validation_1_1single__anonymous__mode.html", null ],
          [ "at_least_one_of_policies", "structarg__router_1_1policy_1_1validation_1_1at__least__one__of__policies.html", null ],
          [ "node_types_must_be_at_end", "structarg__router_1_1policy_1_1validation_1_1node__types__must__be__at__end.html", null ],
          [ "anonymous_mode_must_be_at_end", "structarg__router_1_1policy_1_1validation_1_1anonymous__mode__must__be__at__end.html", null ],
          [ "positional_args_must_have_fixed_count_if_not_at_end", "structarg__router_1_1policy_1_1validation_1_1positional__args__must__have__fixed__count__if__not__at__end.html", null ],
          [ "must_have_at_least_min_count_of_1_if_required", "structarg__router_1_1policy_1_1validation_1_1must__have__at__least__min__count__of__1__if__required.html", null ]
        ] ],
        [ "alias_t", "classarg__router_1_1policy_1_1alias__t.html", "classarg__router_1_1policy_1_1alias__t" ],
        [ "custom_parser", "classarg__router_1_1policy_1_1custom__parser.html", "classarg__router_1_1policy_1_1custom__parser" ],
        [ "default_help_formatter_t", "classarg__router_1_1policy_1_1default__help__formatter__t.html", null ],
        [ "default_value", "classarg__router_1_1policy_1_1default__value.html", "classarg__router_1_1policy_1_1default__value" ],
        [ "dependent_t", "classarg__router_1_1policy_1_1dependent__t.html", "classarg__router_1_1policy_1_1dependent__t" ],
        [ "description_t", "classarg__router_1_1policy_1_1description__t.html", "classarg__router_1_1policy_1_1description__t" ],
        [ "display_name_t", "classarg__router_1_1policy_1_1display__name__t.html", "classarg__router_1_1policy_1_1display__name__t" ],
        [ "error_name_t", "classarg__router_1_1policy_1_1error__name__t.html", "classarg__router_1_1policy_1_1error__name__t" ],
        [ "flatten_help_t", "structarg__router_1_1policy_1_1flatten__help__t.html", null ],
        [ "long_name_t", "classarg__router_1_1policy_1_1long__name__t.html", "classarg__router_1_1policy_1_1long__name__t" ],
        [ "min_max_count_t", "classarg__router_1_1policy_1_1min__max__count__t.html", "classarg__router_1_1policy_1_1min__max__count__t" ],
        [ "min_max_value_t", "classarg__router_1_1policy_1_1min__max__value__t.html", "classarg__router_1_1policy_1_1min__max__value__t" ],
        [ "min_max_value_ct", "classarg__router_1_1policy_1_1min__max__value__ct.html", "classarg__router_1_1policy_1_1min__max__value__ct" ],
        [ "multi_stage_value", "classarg__router_1_1policy_1_1multi__stage__value.html", "classarg__router_1_1policy_1_1multi__stage__value" ],
        [ "has_multi_stage_value", "structarg__router_1_1policy_1_1has__multi__stage__value.html", null ],
        [ "no_result_value", "structarg__router_1_1policy_1_1no__result__value.html", null ],
        [ "none_name_t", "classarg__router_1_1policy_1_1none__name__t.html", "classarg__router_1_1policy_1_1none__name__t" ],
        [ "is_policy", "structarg__router_1_1policy_1_1is__policy.html", null ],
        [ "is_all_policies", "structarg__router_1_1policy_1_1is__all__policies.html", null ],
        [ "has_pre_parse_phase_method", "structarg__router_1_1policy_1_1has__pre__parse__phase__method.html", null ],
        [ "has_parse_phase_method", "structarg__router_1_1policy_1_1has__parse__phase__method.html", null ],
        [ "has_validation_phase_method", "structarg__router_1_1policy_1_1has__validation__phase__method.html", null ],
        [ "has_routing_phase_method", "structarg__router_1_1policy_1_1has__routing__phase__method.html", null ],
        [ "has_missing_phase_method", "structarg__router_1_1policy_1_1has__missing__phase__method.html", null ],
        [ "has_priority", "structarg__router_1_1policy_1_1has__priority.html", null ],
        [ "nearest_mode_like", "classarg__router_1_1policy_1_1nearest__mode__like.html", "classarg__router_1_1policy_1_1nearest__mode__like" ],
        [ "program_addendum_t", "classarg__router_1_1policy_1_1program__addendum__t.html", "classarg__router_1_1policy_1_1program__addendum__t" ],
        [ "program_intro_t", "classarg__router_1_1policy_1_1program__intro__t.html", "classarg__router_1_1policy_1_1program__intro__t" ],
        [ "program_name_t", "classarg__router_1_1policy_1_1program__name__t.html", "classarg__router_1_1policy_1_1program__name__t" ],
        [ "program_version_t", "classarg__router_1_1policy_1_1program__version__t.html", "classarg__router_1_1policy_1_1program__version__t" ],
        [ "required_t", "classarg__router_1_1policy_1_1required__t.html", "classarg__router_1_1policy_1_1required__t" ],
        [ "router", "classarg__router_1_1policy_1_1router.html", "classarg__router_1_1policy_1_1router" ],
        [ "short_form_expander_t", "classarg__router_1_1policy_1_1short__form__expander__t.html", "classarg__router_1_1policy_1_1short__form__expander__t" ],
        [ "short_name_t", "classarg__router_1_1policy_1_1short__name__t.html", "classarg__router_1_1policy_1_1short__name__t" ],
        [ "value_separator_t", "classarg__router_1_1policy_1_1value__separator__t.html", "classarg__router_1_1policy_1_1value__separator__t" ]
      ] ],
      [ "traits", null, [
        [ "always_false", "structarg__router_1_1traits_1_1always__false.html", null ],
        [ "has_value_type", "structarg__router_1_1traits_1_1has__value__type.html", null ],
        [ "underlying_type", "structarg__router_1_1traits_1_1underlying__type.html", null ],
        [ "is_tuple_like", "structarg__router_1_1traits_1_1is__tuple__like.html", null ],
        [ "is_specialisation", "structarg__router_1_1traits_1_1is__specialisation.html", null ],
        [ "is_specialisation_of", "structarg__router_1_1traits_1_1is__specialisation__of.html", null ],
        [ "is_same_when_despecialised", "structarg__router_1_1traits_1_1is__same__when__despecialised.html", null ],
        [ "add_optional", "structarg__router_1_1traits_1_1add__optional.html", null ],
        [ "unpack_and_derive", "classarg__router_1_1traits_1_1unpack__and__derive.html", null ],
        [ "supports_static_cast_conversion", "structarg__router_1_1traits_1_1supports__static__cast__conversion.html", null ],
        [ "has_long_name_method", "structarg__router_1_1traits_1_1has__long__name__method.html", null ],
        [ "has_short_name_method", "structarg__router_1_1traits_1_1has__short__name__method.html", null ],
        [ "has_display_name_method", "structarg__router_1_1traits_1_1has__display__name__method.html", null ],
        [ "has_none_name_method", "structarg__router_1_1traits_1_1has__none__name__method.html", null ],
        [ "has_error_name_method", "structarg__router_1_1traits_1_1has__error__name__method.html", null ],
        [ "has_description_method", "structarg__router_1_1traits_1_1has__description__method.html", null ],
        [ "has_value_separator_method", "structarg__router_1_1traits_1_1has__value__separator__method.html", null ],
        [ "has_maximum_count_method", "structarg__router_1_1traits_1_1has__maximum__count__method.html", null ],
        [ "has_minimum_count_method", "structarg__router_1_1traits_1_1has__minimum__count__method.html", null ],
        [ "has_minimum_value_method", "structarg__router_1_1traits_1_1has__minimum__value__method.html", null ],
        [ "has_maximum_value_method", "structarg__router_1_1traits_1_1has__maximum__value__method.html", null ],
        [ "has_push_back_method", "structarg__router_1_1traits_1_1has__push__back__method.html", null ],
        [ "has_help_data_type", "structarg__router_1_1traits_1_1has__help__data__type.html", null ],
        [ "has_generate_help_method", "structarg__router_1_1traits_1_1has__generate__help__method.html", null ],
        [ "has_parse_method", "structarg__router_1_1traits_1_1has__parse__method.html", null ],
        [ "has_translate_exception_method", "structarg__router_1_1traits_1_1has__translate__exception__method.html", null ],
        [ "has_error_code_translations_type", "structarg__router_1_1traits_1_1has__error__code__translations__type.html", null ],
        [ "arg_extractor", "structarg__router_1_1traits_1_1arg__extractor.html", null ]
      ] ],
      [ "utility", "namespacearg__router_1_1utility.html", [
        [ "utf8", "namespacearg__router_1_1utility_1_1utf8.html", [
          [ "code_point", "namespacearg__router_1_1utility_1_1utf8_1_1code__point.html", [
            [ "range", "classarg__router_1_1utility_1_1utf8_1_1code__point_1_1range.html", "classarg__router_1_1utility_1_1utf8_1_1code__point_1_1range" ],
            [ "iterator", "classarg__router_1_1utility_1_1utf8_1_1code__point_1_1iterator.html", "classarg__router_1_1utility_1_1utf8_1_1code__point_1_1iterator" ]
          ] ],
          [ "iterator", "classarg__router_1_1utility_1_1utf8_1_1iterator.html", "classarg__router_1_1utility_1_1utf8_1_1iterator" ],
          [ "line_iterator", "classarg__router_1_1utility_1_1utf8_1_1line__iterator.html", "classarg__router_1_1utility_1_1utf8_1_1line__iterator" ]
        ] ],
        [ "compile_time_optional", "classarg__router_1_1utility_1_1compile__time__optional.html", "classarg__router_1_1utility_1_1compile__time__optional" ],
        [ "compile_time_string", "classarg__router_1_1utility_1_1compile__time__string.html", "classarg__router_1_1utility_1_1compile__time__string" ],
        [ "create_sequence_cts", "classarg__router_1_1utility_1_1create__sequence__cts.html", null ],
        [ "convert_to_cts", "structarg__router_1_1utility_1_1convert__to__cts.html", null ],
        [ "convert_integral_to_cts", "structarg__router_1_1utility_1_1convert__integral__to__cts.html", null ],
        [ "result", "classarg__router_1_1utility_1_1result.html", "classarg__router_1_1utility_1_1result" ],
        [ "tree_type_recursor_collector", "structarg__router_1_1utility_1_1tree__type__recursor__collector.html", "structarg__router_1_1utility_1_1tree__type__recursor__collector" ],
        [ "unsafe_any_t", "classarg__router_1_1utility_1_1unsafe__any__t.html", "classarg__router_1_1utility_1_1unsafe__any__t" ]
      ] ],
      [ "arg_t", "classarg__router_1_1arg__t.html", "classarg__router_1_1arg__t" ],
      [ "counting_flag_t", "classarg__router_1_1counting__flag__t.html", "classarg__router_1_1counting__flag__t" ],
      [ "default_error_code_translations", "structarg__router_1_1default__error__code__translations.html", null ],
      [ "multi_lang_exception", "classarg__router_1_1multi__lang__exception.html", "classarg__router_1_1multi__lang__exception" ],
      [ "parse_exception", "classarg__router_1_1parse__exception.html", "classarg__router_1_1parse__exception" ],
      [ "flag_t", "classarg__router_1_1flag__t.html", "classarg__router_1_1flag__t" ],
      [ "help_t", "classarg__router_1_1help__t.html", "classarg__router_1_1help__t" ],
      [ "list", "classarg__router_1_1list.html", "classarg__router_1_1list" ],
      [ "mode_t", "classarg__router_1_1mode__t.html", "classarg__router_1_1mode__t" ],
      [ "parser", "structarg__router_1_1parser.html", null ],
      [ "positional_arg_t", "classarg__router_1_1positional__arg__t.html", "classarg__router_1_1positional__arg__t" ],
      [ "root_t", "classarg__router_1_1root__t.html", "classarg__router_1_1root__t" ],
      [ "tree_node", "classarg__router_1_1tree__node.html", "classarg__router_1_1tree__node" ],
      [ "is_tree_node", "structarg__router_1_1is__tree__node.html", null ]
    ] ]
];