#!/usr/bin/env bash

# Copyright (C) 2022-2023 by Camden Mannett.
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE or copy at https://www.boost.org/LICENSE_1_0.txt)

# Run the copyright checker
git diff-index --name-only --cached HEAD | xargs ./scripts/copyright_checker.py date
