// Copyright (C) 2022-2023 by Camden Mannett.
// Distributed under the Boost Software License, Version 1.0.
// (See accompanying file LICENSE or copy at https://www.boost.org/LICENSE_1_0.txt)

#pragma once

/** @file
 *
 * This file is automatically generated by the build system, do not manually modify it.  If you need
 * to change the template, it is located in arg_router/cmake/versioning/version.hpp.in
 */

namespace arg_router
{
/** Library version as a SymVers-style string.
 */
constexpr auto version_string = "1.3.0";
}  // namespace arg_router
